config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#home"
  get "about", to: "pages#about"
  resources :articles do
    resources :comments
  end

  mount ActionCable.server => "/cable"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  before_save :capitalize_title

  validates :title, presence: true, length: { minimum: 3, maximum: 35 },
                                    uniqueness: { case_sensitive: false }
  validates :description, presence: true, length: { minimum: 10 }
  validates :user_id, presence: true
  default_scope -> { order(created_at: :desc) }
  belongs_to :user
  has_many :comments, dependent: :destroy
  # has_many :article_categories
  # has_many :categories, through: :article_categories

  def self.search(search)
    if !search.blank?
      where("title like ?", "%#{search}%")
    end
  end

  def capitalize_title
    self.title.capitalize!
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, length: { minimum: 3, maximum: 200 }
  validates :user_id, presence: true
  validates :article_id, presence: true

  default_scope -> { order(created_at: :desc) }

  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :resources_not_found

  protected

  def resources_not_found
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :select_article, except: [:new, :create, :index]
  before_action :require_owner, only: [:edit, :update, :destroy]

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render "new"
    end
  end

  def edit; end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render "edit"
    end
  end

  def show
    @comment = @article.comments.build
    @comments = @article.comments.paginate(page: params[:page], per_page: 7)
  end

  def index
    @search = Article.search(params[:search])
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article was successfully deleted"
    redirect_to articles_path
  end

  protected

  def resources_not_found
    flash[:danger] = "The article you are looking for could not be found"
    redirect_to root_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def select_article
    @article = Article.find(params[:id])
  end

  def require_owner
    unless current_user == @article.user
      flash[:danger] = "You can only modify your own articles"
      redirect_to root_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article
  before_action :authenticate_user!

  def create
    @comment = @article.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      ActionCable.server.broadcast "comments",
        render(partial: "comments/comment", object: @comment)
      flash[:notice] = "Comment has been created"
    else
      flash.now[:notice] = "Comment has not been created"
    end
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_article
    @article = Article.find(params[:article_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def persisted_comments(comments)
    comments.reject{ |comment| comment.new_record?}
  end
end

app/views/articles/_comments.html.erb
<div class="col-12 xspace">
  <h5>Comments:</h5>
  <div class="col-9 sspace-top">
      <% if @comments.any? %>
        <div id="messages">
          <% persisted_comments(@comments).each do |comment| %>
            <div class="col-12 card text-white bg-dark space">
              <div class="card-body">
                <div class="card-title">
                  <small>
                    <p>
                      <u><%= comment.user.email %></u> -
                      <%= time_ago_in_words(comment.created_at) %> ago.
                    </p>
                  </small>
                </div>
                <h5 class="card-text"><%= comment.body %></h5>
              </div>
            </div>
          <% end %>
        </div>
        <div class="row offset-4 sspace">
          <%= will_paginate @comments %>
        </div>
      <% else %>
        <b><p>There are no comments to display</p></b>
      <% end %>
  </div>

  <% if user_signed_in? %>
    <div class="col-12">
      <%= form_for [@article, @comment], remote: true do |f| %>
        <% if @comment.errors.any? %>
          <div class="container">
            <div class="row error">
              <div class="col-12">
                <div class="card border-danger">
                  <div class="card-header text-danger">
                    <h4>
                      <%= pluralize(@comment.errors.count, "error") %>
                      prohibited this comment from behing saved:
                    </h4>
                  </div>
                  <div class="card-body text-danger">
                    <% @comment.errors.full_messages.each do |msg| %>
                      <ul>
                        <li><%= msg %></li>
                      </ul>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>

        <div class="space space-top">
          <div class="row col-12">
            <b><%= f.label :body, "New comment" %></b>
          </div>

          <div class="row col-md-8 col-lg-6">
            <%= f.text_area :body, class: "form-control" %>
          </div>
        </div>

        <div class="row col-12 space">
          <%= f.submit "Add comment", class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<!-- Displaying errors -->
<%= render "shared/errors", obj: @article %>
<!-- Form -->
<div class="xspace">
  <%= form_for @article do |f| %>
    <div class="space space-top">
      <div class="row col-12">
        <b><%= f.label :title %></b>
      </div>

      <div class="row col-md-8 col-lg-6">
        <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>

    <div class="space">
      <div class="row col-12">
        <b><%= f.label :description %></b>
      </div>

      <div class="row col-md-8 col-lg-6">
        <%= f.text_area :description, class: "form-control" %>
      </div>
    </div>

    <div class="row col-12">
      <%= f.submit "Confirm", class: "btn btn-secondary" %>
    </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<%= render "shared/title", title: "Edit Article" %>

<%= render "form" %>

<div class="row col-12">
  <p>
    <%= link_to "Articles listing", articles_path,
                                    class:"btn btn-secondary button-spacing" %>
  </p>
  <p>
    <%= link_to "Show", article_path(@article),
                        class:"btn btn-secondary" %>
  </p>
</div>

app/views/articles/index.html.erb
<%= render "shared/title", title: "Articles" %>

<div class="row mspace col-12">
  <b><%= link_to "Create new article", new_article_path,
                                       class:"btn btn-secondary" %></b>
</div>

<% if @articles.any? %>
  <%= render "shared/search_box", path: articles_path %>

  <% if @search != [] && @search == nil %>
    <div class="row offset-4 sspace">
      <%= will_paginate %>
    </div>

    <% @articles.each do |article| %>
      <div class="space">
        <div class="card text-white bg-dark col-md-10 col-sm-12">
          <div class="card-header border-secondary">
            <h5><%= article.title %></h5>
          </div>
          <div class="card-body">
            <p>
              <b>Writer: &nbsp;</b>
              <u><%= link_to  article.user.email, "#", class: "text-white" %></u>
            </p>

            <small>
              <p>
                <b>Created at: &nbsp;</b><%= time_ago_in_words(article.created_at) %> ago.
                <% if time_ago_in_words(article.created_at) !=
                      time_ago_in_words(article.updated_at) %>
                  <b>| Last updated: </b><%= time_ago_in_words(article.updated_at) %> ago.
                <% end %>
              </p>
              <%= link_to "Show", article_path(article),
                                  class:"btn btn-secondary btn-sm" %>

              <% if user_signed_in? && article.user == current_user %>
                <%= link_to "Edit", edit_article_path(article),
                                    class:"btn btn-secondary btn-sm" %>
                <%= link_to "Delete", article_path(article),
                                      method: :delete,
                                      data: {confirm: "Are you sure?"},
                                      class:"btn btn-secondary btn-sm" %>
              <% end %>


            </small>
          </div>
        </div>
      </div>
    <% end %>

    <div class="row offset-4 sspace">
      <%= will_paginate %>
    </div>
  <% end %>
<% else %>
  <div class="row xspace">
    <div class="center col-12 text-danger">
      <h5>There are no articles to display</h5>
    </div>
  </div>
<% end %>

app/views/articles/new.html.erb
<%= render "shared/title", title: "Create Article" %>

<%= render "form" %>

<div class="row col-12">
  <b>
    <%= link_to "Back to articles listing", articles_path,
                                            class: "btn btn-secondary" %>
  </b>
</div>

app/views/articles/show.html.erb
<%= render "shared/title", title: "Title: " + @article.title %>

<div class="mspace">
  <div class="card text-white bg-dark">
    <div class="card-header border-secondary">
      <h5 class="center">Description:</h5>
    </div>
    <div class="card-body">
      <p class="card-title"><%= @article.description %></p>
    </div>
  </div>
</div>

<div class="row mspace">
  <div class="col-xl-5 col-lg-6 col-md-7">
    <div class="card border-secondary">
      <div class="card-body">
        <h5 class="card-text"><b>Writer:</b>
          <u>
            <%= link_to @article.user.email, "#", class: "text-dark" %>
          </u>
        </h5>

        <h5 class="card-text"><b>Created at:</b>
          <%= time_ago_in_words(@article.created_at) %> ago.
        </h5>
        <% if time_ago_in_words(@article.created_at) !=
              time_ago_in_words(@article.updated_at) %>
          <h5 class="card-text"><b>Last updated: </b>
            <%= time_ago_in_words(@article.updated_at) %> ago.
          </h5>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render "comments" %>

<div class="row col-12">
  <p>
    <%= link_to "Articles listing", articles_path,
                                    class:"btn btn-secondary button-spacing" %>
  </p>
  <% if user_signed_in? && @article.user == current_user %>
    <p>
      <%= link_to "Edit", edit_article_path(@article),
                          class:"btn btn-secondary button-spacing" %>
    </p>
    <p>
      <%= link_to "Delete", article_path(@article),
                          method: :delete,
                          data: {confirm: "Are you sure?"},
                          class:"btn btn-secondary" %>
    </p>
  <% end %>
</div>

app/views/comments/_comment.html.erb
<div class="col-12 card text-white bg-dark space">
  <div class="card-body">
    <div class="card-title">
      <small>
        <p>
          <u><%= comment.user.email %></u> -
          <%= time_ago_in_words(comment.created_at) %> ago.
        </p>
      </small>
    </div>
    <h5 class="card-text"><%= comment.body %></h5>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer mt-5 py-5">
  <div class="container">
    <span class="text-muted">Made by Vinícius.</span>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-12 center">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>' >
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Alpha Blog", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button"
                                 data-toggle="collapse"
                                 data-target="#navbarSupportedContent"
                                 aria-controls="navbarSupportedContent"
                                 aria-expanded="false"
                                 aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#"
                                              id="navbarDropdown"
                                              role="button"
                                              data-toggle="dropdown"
                                              aria-haspopup="true"
                                              aria-expanded="false">
            Actions
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Articles", articles_path, class:"dropdown-item" %>
            <%= link_to "Categories", "#", class:"dropdown-item" %>
            <%= link_to "Bloggers", "#", class:"dropdown-item" %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to "New Article", new_article_path, class:"nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Articles", articles_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Categories", "#", class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Bloggers", "#", class:"nav-link" %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "#", :class=> "nav-link" do %>
              <span><i class="fas fa-user"></i></span>
              <%= current_user.email %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to "Signout", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Signup", new_user_registration_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <%= render "layouts/messages" %>
    <div class="container body-margin">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<%= render "shared/title", title: "About" %>

<div class="row">
  <div class="col-12">
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis convallis
      lectus sed cursus condimentum. In a turpis metus. Aliquam erat volutpat.
      Proin gravida blandit nisl quis vulputate. Pellentesque id dignissim tortor.
      Vestibulum quis magna eget urna convallis bibendum. Nunc viverra tempor mi,
      a commodo orci egestas nec. In hac habitasse platea dictumst. Donec mollis
      orci sed interdum tempus.
    </p>
  </div>
  <div class="col-12">
    <p>
      Duis ultricies urna vel ex feugiat scelerisque. Ut a felis eu purus semper
       pulvinar. Aenean at vulputate mauris. Sed lacinia dolor vitae justo bibendum
       interdum. Mauris vel leo arcu. Ut eget hendrerit libero. Quisque vehicula,
       quam vitae gravida aliquam, enim diam egestas tellus, ut aliquet quam purus
        ornare augue. Aliquam erat volutpat. Maecenas vitae laoreet tellus.
      </p>
  </div>
  <div class="col-12">
    <p>
      Morbi vitae mi nibh. In at erat quis augue egestas efficitur a vitae urna.
       Sed ullamcorper tristique interdum. Nullam feugiat felis quis elementum
       fringilla. Nam porta sagittis scelerisque. Aenean eros arcu, pulvinar vitae
       dui id, aliquam feugiat arcu. Ut vitae rhoncus lectus, vitae maximus mauris.
       Praesent justo eros, tincidunt nec nibh eu, gravida vehicula ligula. Sed at
       eleifend urna. Ut nisi mauris, facilisis vel blandit nec, convallis ac leo.
       Aliquam mollis dui dui, non sodales nunc vehicula vitae. Sed euismod sapien
       eget lacus semper posuere.
     </p>
  </div>
  <div class="col-12">
    <p>
      Cras ut nibh eget eros venenatis sagittis ac sed massa. Ut tempor rutrum
      massa, sit amet blandit lectus pulvinar sed. Etiam in arcu dolor. Donec
      elementum odio tincidunt lorem ultrices mattis. Morbi auctor, quam eu placerat
       maximus, metus urna tempus eros, eleifend dictum dui mi nec mauris. Nulla
       id nisi vehicula, blandit enim in, venenatis augue. Maecenas in faucibus
       sapien.
     </p>
  </div>
  <div class="col-12">
    <p>
      Suspendisse potenti. Nullam molestie cursus sagittis. Aenean et velit id
      diam condimentum sodales vel eu felis. Aliquam dignissim magna nisl, ut
      volutpat libero malesuada sit amet. Curabitur eu eros vitae odio eleifend
      semper non sit amet lacus. Sed id turpis interdum magna porttitor facilisis
      at id ipsum. Phasellus ac pretium lacus, at porttitor lectus. Sed porta
      feugiat elit et posuere. In pharetra lectus vel aliquam viverra. Donec in
      odio id erat commodo laoreet id eu turpis. Vestibulum tempus iaculis tempor.
      Etiam tincidunt condimentum molestie.
    </p>
  </div>
</div>

<div class="row">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <b><%= link_to "Alpha Blog", articles_path %></b>
      </li>
      <li class="breadcrumb-item"><b><%= link_to "Home", root_path %></b></li>
    </ol>
  </nav>
</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
  <h1 class="display-3 space">ALPHA BLOG</h1>
  <p>Community for creation and share of articles.</p>
  <p><%= link_to "Sign up now", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
</div>

<div class="row">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <b><%= link_to "Alpha Blog", articles_path %></b>
      </li>
      <li class="breadcrumb-item"><b><%= link_to "About", about_path %></b></li>
    </ol>
  </nav>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="container">
    <div class="row error">
      <div class="col-12">
        <div class="card border-danger">
          <div class="card-header text-danger">
            <h4>
              <%= pluralize(obj.errors.count, "error") %>
              prohibited this from behing saved:
            </h4>
          </div>
          <div class="card-body text-danger">
            <% obj.errors.full_messages.each do |msg| %>
              <ul>
                <li><%= msg %></li>
              </ul>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_search_box.html.erb
<div class="xspace col-12">
  <%= form_tag path, :method => "get" do %>
    <div class="row">
      <b><%= label_tag(:search, "Search for an article:") %></b>
    </div>
    <div class="row sspace">
      <%= text_field_tag :search, params[:search] %>
    </div>
    <div class="row space">
      <%= submit_tag("Search", :name => nil, class:"btn btn-secondary btn-sm") %>
    </div>
  <% end %>

  <% if @search == [] %>
    <div class="row form-inline">
      <%= link_to "<i class='far fa-window-close fa-lg'></i> ".html_safe, path,
          class:"nav-link close-symbol" %>
      <h5>Article not found!</h5>
    </div>
  <% elsif @search != nil %>
    <div class="row form-inline">
      <%= link_to "<i class='far fa-window-close fa-lg'></i> ".html_safe, path,
        class:"nav-link close-symbol" %>
      <h5>Article found!</h5>
    </div>
    <% @search.each do |article| %>
      <div class="space">
        <div class="card border-dark col-md-10 col-sm-12">
          <div class="card-header border-dark">
            <h5><%= article.title %></h5>
          </div>
          <div class="card-body">
            <p>
              <b>Writer: &nbsp;</b>
              <u><%= link_to  article.user.email, "#", class: "text-dark" %></u>
            </p>

            <small>
              <p>
                <b>Created at: &nbsp;</b><%= time_ago_in_words(article.created_at) %> ago.
                <% if time_ago_in_words(article.created_at) !=
                      time_ago_in_words(article.updated_at) %>
                  <b>| Last updated: </b><%= time_ago_in_words(article.updated_at) %> ago.
                <% end %>
              </p>
              <%= link_to "Show", article_path(article),
                                  class:"btn btn-secondary btn-sm" %>
              <% if user_signed_in? && article.user == current_user %>
                <%= link_to "Edit", edit_article_path(article),
                                    class:"btn btn-secondary btn-sm" %>
                <%= link_to "Delete", article_path(article),
                                      method: :delete,
                                      data: {confirm: "Are you sure?"},
                                      class:"btn btn-secondary btn-sm" %>
              <% end %>
            </small>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_title.html.erb
<div class="row mspace">
  <div class="center col-12">
    <h1><%= title %></h1>
  </div>
</div>